style_edition = "2024"
# Global max line widths
max_width = 100
# Comments
comment_width = 80
wrap_comments = true
format_code_in_doc_comments = true
# Imports
imports_granularity = "Crate"
reorder_imports = true
group_imports = "StdExternalCrate"
# Code Structure
where_single_line = true
use_small_heuristics = "Max"
use_field_init_shorthand = true